name: build

on:
  push:
    branches:
    - '**'
  workflow_dispatch:
    branches:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  rust-32-on-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Environment
      shell: bash
      run: |
        lscpu 2>/dev/null && echo --- || true
        env | sort
        echo ---
        rustup target list || true

    - name: Rust
      shell: bash
      run: |
        rustup target add i686-pc-windows-msvc || true
        rustc --version --verbose
        cd bindings/rust
        cargo test --release --target=i686-pc-windows-msvc
